### ISSUE TITLE
Rewrite it in brainfuck

### ISSUE THREAD

**Issue by nico-abram** [gamozolabs/helicopter_game#1]
Rust is well known to have [soundness issues](https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+label%3A%22I-unsound+%F0%9F%92%A5%22), so I propose you rewrite this critical software in a truly safe programming language, such as brainfuck

**Comment by gamozolabs** [comment]
Unfortunately at this point we have invested too much into this tool. A full rewrite would be way too much work. Potentially we could look at writing future components in brainfuck, but as of now there's just too much legacy code that needs to be supported.
